// lens-widgets-react/src/FollowOnLens.tsx
import LensIcon from './LensIcon'
import { Theme, Size } from './types' 
import { getContainerStyle, getTextStyle } from './utils'

export function FollowOnLens({
  handle,
  theme = Theme.default,
  size = Size.medium,
  title
} : {
  handle: string,
  theme?: Theme,
  size?: Size,
  title?: string
}) {
  function navigate() {
    if (!handle.includes('.lens')) {
      handle = handle + '.lens'
    }
    const uri = `https://www.lensfrens.xyz/${handle.toLowerCase()}/follow`
    window.open(uri, '_newtab')
  }

  function handleWithoutLens() {
    if (handle.includes('.lens')) {
      handle = handle.split('.')[0]
    }
    return '@' + handle
  }

  if (!title) {
    title = `Follow ${handleWithoutLens()} on Lens`
  }

  return (
    <button onClick={navigate} style={getContainerStyle(theme, size)}>
      <LensIcon theme={theme} size={size} />
      <p style={getTextStyle(theme, size)}>{title}</p>
    </button>
  )
}

// lens-widgets-svelte/src/lib/FollowOnLens.svelte
<script lang="ts">
  import './styles.css'
  import { Theme, Size } from './types' 
  import { getContainerStyle, getTextStyle } from './utils'
  import LensIcon from './LensIcon.svelte'

  export let handle: string
  export let size = Size.medium
  export let theme = Theme.default
  export let title:string

  if (!title) {
    title = `Follow ${handleWithoutLens(handle)} on Lens`
  }

  function navigate() {
    if (!handle.includes('.lens')) {
      handle = handle + '.lens'
    }
    const uri = `https://www.lensfrens.xyz/${handle.toLowerCase()}/follow`
    window.open(uri, '_newtab')
	}

  function handleWithoutLens(handle: string) {
    if (handle.includes('.lens')) {
      handle = handle.split('.')[0]
    }
    return '@' + handle
  }
</script>

<button style={getContainerStyle(theme, size)} class="button" on:click={navigate}>
  <LensIcon theme={theme} size={size} />
  <p style={getTextStyle(theme, size)} class="text">
    {title}
  </p>
</button>
